# Generated by Django 4.0.5 on 2022-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
